language: node_js
node_js: node

before_install:
  - openssl aes-256-cbc -K $encrypted_5a0f716349ce_key -iv $encrypted_5a0f716349ce_iv -in .travis/deploy_key.pem.enc -out .travis/deploy_key.pem -d
  - chmod 600 .travis/deploy_key.pem

script: npm run-script gulp

after_success:
  - eval `ssh-agent -s`
  - ssh-add .travis/deploy_key.pem
  - cd public
  - git init
  - git config user.email "wall-display-deploy@theunlink.com"
  - git config user.name "Deploy"
  - git add .
  - git commit -m "overwrite"
  - git remote add deploy git@github.com:azdle/wall-display.git
  - git push --force deploy master:gh-pages