language: node_js
node_js: node

before_install:
  - openssl aes-256-cbc -K $encrypted_5a0f716349ce_key -iv $encrypted_5a0f716349ce_iv -in deploy_key.pem.enc -out deploy_key.pem -d
  - chmod 600 .travis/deploy_key.pem
  - ssh-add .travis/deploy_key.pem

after_success:
  - cd public && git init
  - cd public && git add .
  - cd public && git commit -m "overwrite"
  - cd public && git remote add deploy DEPLOY_REPO_URI_GOES_HERE
  - cd public && git push --force deploy master:gh-pages